CREATE TABLE IF NOT EXISTS user_role (
    role_id INT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    is_delete BIT(1),
    PRIMARY KEY (role_id , user_name),
    FOREIGN KEY (user_name)
        REFERENCES `user` (user_name),
    FOREIGN KEY (role_id)
        REFERENCES `role` (role_id)
);

INSERT INTO `user_role` (`role_id`, `user_name`, `is_delete`) VALUES
(3, 'john_doe', 0),
(2, 'jane_smith', 0),
(2, 'michael_jones', 0),
(2, 'emily_wilson', 0),
(2, 'ryan_taylor', 0),
(2, 'olivia_davis', 0),
(1, 'adam_martin', 0),
(1, 'lily_thompson', 0),
(1, 'nathan_anderson', 0),
(1, 'sophia_miller', 0),
(1, 'william_baker', 0),
(1, 'ava_wright', 0),
(1, 'alexander_morris', 0),
(1, 'chloe_hall', 0),
(1, 'daniel_robinson', 0),
(1, 'ella_hill', 0),
(1, 'matthew_jackson', 0),
(1, 'grace_evans', 0),
(1, 'jacob_clark', 0),
(1, 'amelia_turner', 0),
(1, 'oliver_carter', 0),
(1, 'mia_fisher', 0),
(1, 'ethan_nelson', 0),
(1, 'isabella_harrison', 0),
(1, 'noah_wood', 0),
(1, 'sophie_walker', 0),
(1, 'logan_mitchell', 0),
(1, 'ava_watson', 0),
(1, 'liam_rogers', 0),
(1, 'olivia_fletcher', 0),
(1, 'mason_campbell', 0),
(1, 'amelia_hudson', 0),
(1, 'jack_stevens', 0),
(1, 'harper_wells', 0),
(1, 'benjamin_barnes', 0),
(1, 'ava_murray', 0),
(1, 'samuel_williams', 0),
(1, 'grace_cooper', 0),
(1, 'dylan_jenkins', 0),
(1, 'aubrey_cox', 0),
(1, 'jackson_hughes', 0),
(1, 'emma_ferguson', 0),
(1, 'owen_cole', 0),
(1, 'abigail_ward', 0),
(1, 'aiden_turner', 0),
(1, 'ella_knight', 0),
(1, 'luke_porter', 0),
(1, 'mia_cunningham', 0),
(1, 'carter_watts', 0),
(1, 'scarlett_brooks', 0);
